package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
)

/** This program will determine the position of our submarine based on the commands
/** found in instructions.txt
**/

type Position struct {
	Horizontal int
	Depth      int
}

func main() {
	p := Position{}
	p.open()
	// First we must read in the commands and store the commands in a local variable

}

func (p *Position) open() {

	// Opens the instructions.txt file and stores it in f
	f, err := os.Open("instructions.txt")
	if err != nil {
		log.Println(err)
	}

	// Splits on newlines
	scanner := bufio.NewScanner(f)

	// Iterate through each line of f
	for scanner.Scan() {
		fmt.Println(scanner.Text())
	}

	// Handle any errors generated by scanner.Scan()
	if err := scanner.Err(); err != nil {
		log.Println(err)
	}

}
